---
ActionDispatch::Routing::Mapper.acts_like?:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.alias_attribute:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.anonymous?:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.as_json:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.attr_internal:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.attr_internal_accessor:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.attr_internal_reader:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.attr_internal_writer:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.blank?:
  types:
  - 'true'
  - 'false'
  skip: false
ActionDispatch::Routing::Mapper.cattr_accessor:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.cattr_reader:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.cattr_writer:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.class_attribute:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.concern:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.concerning:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.const_missing:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.deep_dup:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.delegate:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.delegate_missing_to:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.deprecate:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.descendants:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.duplicable?:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.gem:
  types:
  - undefined
  skip: true
ActionDispatch::Routing::Mapper.guess_for_anonymous:
  types:
  - undefined
  skip: true
ActionDispatch::Routing::Mapper.html_safe?:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.in?:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.instance_values:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.instance_variable_names:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.load_dependency:
  types:
  - undefined
  skip: true
ActionDispatch::Routing::Mapper.mattr_accessor:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.mattr_reader:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.mattr_writer:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.method_visibility:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.module_parent:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.module_parent_name:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.module_parents:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.normalize_name:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.normalize_path:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.presence:
  types:
  - Object
  skip: false
ActionDispatch::Routing::Mapper.presence_in:
  types:
  - Object
  skip: false
ActionDispatch::Routing::Mapper.present?:
  types:
  - 'true'
  - 'false'
  skip: false
ActionDispatch::Routing::Mapper.pry:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.rake_extension:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.redefine_method:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.redefine_singleton_method:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.remove_possible_method:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.remove_possible_singleton_method:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.require_dependency:
  types:
  - undefined
  skip: true
ActionDispatch::Routing::Mapper.require_or_load:
  types:
  - undefined
  skip: true
ActionDispatch::Routing::Mapper.silence_redefinition_of_method:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.subclasses:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.thread_cattr_accessor:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.thread_cattr_reader:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.thread_cattr_writer:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.thread_mattr_accessor:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.thread_mattr_reader:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.thread_mattr_writer:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.to_json:
  types:
  - undefined
  skip: true
ActionDispatch::Routing::Mapper.to_param:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.to_query:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.try:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.try!:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper.unloadable:
  types:
  - undefined
  skip: true
ActionDispatch::Routing::Mapper.with_options:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#acts_like?:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#as:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#as_json:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#authenticate:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#authenticated:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#blank?:
  types:
  - 'true'
  - 'false'
  skip: false
ActionDispatch::Routing::Mapper#class_eval:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#collection:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#concern:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#concerns:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#constraints:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#constraints_for:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#controller:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#deep_dup:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#default_url_options:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#default_url_options=:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#defaults:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#delete:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#devise_confirmation:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#devise_for:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#devise_omniauth_callback:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#devise_password:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#devise_registration:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#devise_scope:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#devise_session:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#devise_unlock:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#direct:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#draw:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#duplicable?:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#gem:
  types:
  - undefined
  skip: true
ActionDispatch::Routing::Mapper#get:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#has_named_route?:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#html_safe?:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#in?:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#instance_values:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#instance_variable_names:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#load_dependency:
  types:
  - undefined
  skip: true
ActionDispatch::Routing::Mapper#match:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#member:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#mount:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#namespace:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#nested:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#new:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#options:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#patch:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#post:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#presence:
  types:
  - Object
  skip: false
ActionDispatch::Routing::Mapper#presence_in:
  types:
  - Object
  skip: false
ActionDispatch::Routing::Mapper#present?:
  types:
  - 'true'
  - 'false'
  skip: false
ActionDispatch::Routing::Mapper#pry:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#put:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#raise_no_devise_method_error!:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#raise_no_secret_key:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#redirect:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#require_dependency:
  types:
  - undefined
  skip: true
ActionDispatch::Routing::Mapper#require_or_load:
  types:
  - undefined
  skip: true
ActionDispatch::Routing::Mapper#resolve:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#resource:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#resources:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#resources_path_names:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#root:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#scope:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#set_omniauth_path_prefix!:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#shallow:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#shallow?:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#to_json:
  types:
  - undefined
  skip: true
ActionDispatch::Routing::Mapper#to_param:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#to_query:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#try:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#try!:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#unauthenticated:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#unloadable:
  types:
  - undefined
  skip: true
ActionDispatch::Routing::Mapper#with_default_scope:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#with_devise_exclusive_scope:
  types:
  - undefined
  skip: false
ActionDispatch::Routing::Mapper#with_options:
  types:
  - undefined
  skip: false
